server:
  port: 9001
#-----------------------------------------------------------------------------
# configuration los endpoints
management:
  endpoints:
    web:
      base-path: '/customer/actuator'
      exposure:
        include: "*" #activar el resto actuator. /info, /health, /metrics, /trace, ...

eureka:
  instance:
    status-page-url: http://127.0.0.1:9001${management.endpoints.web.base-path}/info
    health-check-url-path: http://127.0.0.1:9001${management.endpoints.web.base-path}/health

  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8099/eureka/
      # healthcheck: # Activar la prueba de vida del servicio
      #   enabled: true
    ## enabled: false # desactivar el servicio

info: # Este Actuator Muestra información arbitraria de nuestra aplicación.
  project:
    name: ms-store-customer
    description: store customer
    version: 1.0.0