server:
 port: 9000
 
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/productbd
    username: postgres
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

#eureka:
#  instance:
#    statusPageUrlPath: ${management.endpoints.web.base-path}/info
#    healthCheckUrlPath: ${management.endpoints.web.base-path}/health
#  client:
#    serviceUrl:
#      defaultZone: http://locahost:8011/eureka/
      #defaultZone: http://primary:8011/eureka/,http://secondary:8012/eureka/,http://tertiary:8013/eureka/
info:
  project:
    name: ms-store-shopping
    description: Store Shopping
    version: 1.0.0
management:
  endpoints:
    web:
      base-path: '/shopping/actuator'
      exposure:
        include:
        - "*"
#hystrix:
  #dashboard:
   # proxy-stream-allow-list: '*'
#feign:
 # hystrix:
  #  enabled: true